### PR TITLE
Documenting format syntax, improving robustness, documenting custom format fns

### LINKED ISSUE #9: support for multiple types as options
It would be great if we could write:

```
@typed argument: class1, class2
   specifies bla.
```

and it would be rendered like
```
@param argument (`class1` or `class2`)\cr specifies bla.
```
e.g.

### PR DESCRIPTION
**Pull request by dgkf**
Closes #9, tagging @danielinteractive for interest (edit: [docs now published here](https://openpharma.github.io/roxytypes/reference/tags.html#custom-type-parsing-function))

Adds proposal in #9. However, this does not provide a helper function. I think this is a reasonable compromise. Providing helper functions for splitting strings on commas is inherently package-specific since commas can be valid class names and might otherwise be expected to work out-of-the-box.

Included in the documentation under `?tags` and `?typed`, there is an example for multi-class formatting. 

Now, by using a custom function one loses the built-in syntax handling. For example, naively wrapping in backticks would render `[package::fn()]` as a inline code instead of relying on roxygen2 to manage the reference. It's for this reason that I would still recommend using a plain literal, even for multiclass definitions:

```
#' @typed arg: "`character(1L)` or [special_class]"
```

### CODE REVIEW

**Comment by danielinteractive** [comment]
Thanks @dgkf for this!
So I tried to use this now in [Genentech/jmpost@`d5b8f34` (#174)](https://github.com/Genentech/jmpost/pull/174/commits/d5b8f340f5e2b6aec5043ad4ff7904058008a1a1)
However I am observing that e.g. 
image
is giving the output:
image
which is not what I would like, the output should be still:
image
what I can I do better here wrt using `roxytypes`?

**Comment by dgkf** [comment]
Very interesting. I'd chalk this up to a bug - or at least an unintended behavior. I added a test for the interpreted string, but not the styled roxygen output, and this is a bit surprising. 

I think the issue is with how roxygen interprets the `` "`code`" `` style. It seems to be interpreting ``"` .. `"`` as a special delimiter? I didn't anticipate that! I'll investigate and hopefully have a fix up soon.

**Comment by dgkf** [comment]
After digging into this more, I realized it was because the format is being provided by the `Config` in `DESCRIPTION` (which masks the default format and therefore won't leverage any of the default type syntax handling).

In that sense, this is "working as intended", but I'm not satisfied with how it was an all-or-nothing choice between benefiting from the default syntax and doing something custom. 

I pushed an update today which now applies a default format for _each field_ (`type`, `description`) instead of holistically for formatting the whole tag. Internally, each field gets its own S3 class and given a `as.character` method so that `glue` can apply the formatting for us. This means that your custom format will now pick up the default handling to preserve literals.

However, part of this change means that the default `type` formatting will _also_ continue to insert backticks in the "normal" case, so @danielinteractive it should be good if you use the latest version and update your `DESCRIPTION` with:

```diff
- Config/roxytypes: list(format = "(`{type}`)\\cr {description}")
+ Config/roxytypes: list(format = "({type})\\cr {description}")
```

I tested it on `jmpost` and this issue looks cleared up. Let me know if you see anything else that isn't as straightforward as you'd like.

**Comment by danielinteractive** [comment]
Super, thanks @dgkf !

**Comment by danielinteractive** [comment]
Just tested, and can confirm this solves the issue. thanks again!

**Pull request merged**
